name: client
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.9

environment:
  sdk: ">=2.2.0 <3.0.0"
dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  video_player: ^0.10.11+2
  flutter_time_axis:
     git: https://github.com/luhenchang/flutter_time_axis.git
  flutter_custom_calendar: ^1.0.4+0.5
  flutter_ijkplayer: ^0.3.5+1
  path_drawing: 0.4.1+1
  chewie: ^0.9.10
  flutter_screenutil: ^0.5.1
  cupertino_icons: ^0.1.2
  flutter_spinkit: ^3.1.0
  flutter_easyrefresh: ^2.0.3
  photo_view: ^0.4.2
  extended_image: ^1.0.0
  flutter_swiper: ^1.1.6
  city_pickers: ^0.1.28
  flutter_datetime_picker: ^1.3.8
  dio: ^3.0.9
  # fluttertoast: ^3.1.0
  shared_preferences: ^0.5.1
  qr_flutter: ^3.1.0
  flutter_echarts: ^1.1.3
  fluwx: ^2.1.0
  web_socket_channel: ^1.1.0
  fluro: ^1.6.1
  amap_location: ^0.2.0
  location_permissions: ^2.0.0
  permission_handler: ^4.0.0
  svgaplayer_flutter: ^1.1.0
  path_provider: ^1.6.5
  package_info: ^0.4.0+3
  flutter_html: ^0.11.1
  wakelock: ^0.1.4+1
  webview_flutter: ^0.3.15+1
  # fake_alipay: ^0.2.3
  image_gallery_saver: ^1.2.2
  image_picker: ^0.6.7+1
  cached_network_image: ^2.2.0+1
  connectivity: ^0.4.9
  audioplayers: ^0.13.1
  json_serializable: ^2.0.0
  json_annotation: ^2.0.0
  equatable: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  qntools:
    path: ../qntools/
  fluttertoast:
    path: ../FlutterToast
  alipay_kit:
    path: ../alipay_kit

  build_runner: ^1.3.1
  json_serializable: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/login/
    - assets/mine/
    - assets/index/
    - assets/zhibo/
    - assets/dianpu/
    - assets/set/
    - assets/shop/
    - assets/foods/
    - assets/tabbar/
    - assets/gongyingshang/
    - assets/province.json
    - assets/pin_jump.svga
    - assets/angel.svga
    - assets/mutiMask.svga
    - assets/zhubozhenmei.svga
    - assets/ani1.svga
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
